config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name LIKE ?","%#{params[:query]}%")
    else
      @flats = Flat.all
    end
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path
  end

  private

  def flat_params
    require_params(:flats).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h1>All Flats</h1>

<div class="input-group">
  <input type="search" name="query" class="form-control rounded" placeholder="Search" aria-label="Search"
    aria-describedby="search-addon" value="<%= params[:query] %>"/>
  <button type="button" class="btn btn-outline-primary">search</button>
</div>

  <div>
   <% @flats.each do |f|%>
     <div>
      <h4><%= f.name %></h4>
      <p><%= f.address %></h4>
      </br>
      <h4><%= f.price_per_night %></h4>
      <h4><%= f.number_of_guests %></h4>
      <div class="flat-card-actions">
              <%= link_to 'More info', flat_path(f) %>
              <%= link_to 'Edit', edit_flat_path(f), class: 'ml-3 text-warning' %>
              <%= link_to "Remove", flat_path(f),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: 'ml-3 text-danger'
              %>
        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>